apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: achat-groupe
  labels:
    app: achat-groupe
spec:
  rules:
    - host: achat-groupe.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: achat-groupe
                port:
                  number: 80
